---
title: <small>An introduction to digital open <br>research in clinical psychology</small>
author: <small>Matthias Weiler</small>
date: <small>04.03.2019</small>
output:
  revealjs::revealjs_presentation:
    theme: black
    center: TRUE
    self_contained: FALSE
    incremental: TRUE
    reveal_plugins: ["chalkboard"]
    reveal_options:
      chalkboard: 
      readonly: FALSE
---

# <small> What did we do last Saturday?</small>

----

We looked at several research tools

----

... left our comfort zones

----

... and created the templates  
for the presentations

----

Any questions or anything to add?



# <small>Last Saturday's homework</small>

----

Who got an account at https://osf.io?

----

Who downloaded and installed [Zotero](https://www.zotero.org/)?

----

Who managed to upload his/her  
presentations to GitHub?



# <small>Today:<br>Your personal open science project</small>

----

Who has hopes about the research project?

----

Who has fears ...?

----

Who has questions ...?



# <small>Basic rule set</small>

----

\#1 Don't panic

----

\#2 If you do panic look at rule \#1

----

\#3 Plan what you are going to do

----

\#4 Do what you were planning to do

----

\#5 Write down what you have actually done

----

Any questions?


# <small>Proposal presentations</small>

----

## <small>Choose one of the following topics</small>

- Analyze Google trends
- Analyze Twitter data
- Do a sentiment analysis
- Do a social network analysis

----

Prepare a short talk  
(3 minutes max)

----

Prepare slides for your talk  
(in GitHub pages)

----

Slides should include  
introduction, methods,  
proposed analyses and  
references

----

Any questions?



# <small>Proposal reviews</small>

----

After each talk there will be  
time for questions - use it

----

After the last talk the two  
"best" projects from each  
university are selected

----

Who should select the projects?

----

How would you like to  
select the projects?

----

Any other suggestions?

----

Any questions?



# <small>After the reviews</small>

----

Apply the suggested  
changes from the review

----

Add your research project to  
the "Research projects" section  
of the course in the OSF

----

Register your research project in  
the OSF using the Preregistration  
Template from AsPredicted.org 

----

Connect your GitHub repository to  
your research project in the OSF

----

Any questions?



# <small>Research projects</small>

----

You will participate in one of  
the four final research projects  

----

You will work in mixed teams  
(i.e. Crete and Thessaloniki)

----

Any questions?



# <small>Some example projects</small>

----

## <small>Research on seasonal depression</small>

- Analyze Google trends for terms  
like "depression" or "feeling blue"

## <small>Would people rather talk about <br>panic attacks or social anxiety?</small>

- Compare number of tweets on  
\#panic and #socialanxiety

## <small>Are social psychologists more <br>social than clinical psychologists?</small>

- Make a social network analysis  
on authorship in journals



# <small>Any questions left?</small>



# <small>Any fears left?</small>



# <small>Any hope left?</small>



# <small>Preview: next session</small>

----

"Present and review your research proposals"



# <small>Homework</small>

----

Prepare the presentations  
for your research proposals  
in GitHub Pages



# <small>Don't panic</small>



# <small>Thank you for your attention</small>
